[book]
title = "My Mini Rust Playground"
authors = ["Prasiddh"]
language = "en"

[build]
create-missing = true

[output.html]
default-theme = "light"
additional-css = ["theme/custom.css"]

[output.html.playground]
runnable = true
editable = true
copyable = true
copy-js = true
line-numbers = false

[rust]
edition = "2021"


